-- 第 3 周：问卷选题从「纯热度」改为「MMR 多样性排序」。
-- 幂等：可重复执行。
--
-- 前置：001_init.sql（cluster_id 列）、003_vec_halfvec.sql（vec 列，MMR 的输入）。

-- ============================================================
-- mmr_rank —— 问卷候选池的多样性排序位次
-- ============================================================
-- ⚠️ **为什么不是聚类。** 第 9 节原计划是「PCA + k-means → 每簇选代表」。
--    2026-08-14 实测三个诊断，这份数据不支持那个方案：
--
--      silhouette ≈ 0.035（全线，且随 N 单调下降 → 定不出 N）
--      ARI 跨种子 ≈ 0.48   （换个随机种子，一半簇结构就变了）
--
--    动画简介的 embedding 空间是**连续体**不是分离团块 —— 题材本就渐变。
--    而回头看目标：要的是「选 N 部覆盖口味空间的代表」，这是**多样性问题**
--    不是聚类问题。MMR（最大边际相关）直接优化它：
--
--      每轮选 argmax[ λ·热度 − (1−λ)·与已选集合的最大相似度 ]
--
--    实测对比（N=30，λ=0.5，冗余 = 选中集合的两两余弦均值，越低越好）：
--
--      纯热度（原实现）    冗余 0.4552   中位热度 44,146
--      k-means 每簇代表    冗余 0.3994   中位热度 37,092
--      MMR λ=0.5           冗余 0.3781   中位热度 41,040   ← 两项都更优
--      （随机对照）        冗余 0.3627
--
--    k-means 降冗余是靠牺牲热度换的，MMR 严格占优。
--    ⚠️ 而且 MMR **确定性、无随机种子** —— 顺带解决了 ARI≈0.48 暴露的
--       「结果不可复现」问题，这对第 5 周评测是硬要求。
--
-- ⚠️ **cluster_id 不废弃。** 第 10 节的冷启动曲线里「内容簇选题」本来就是
--    四条对照线之一，它继续作为 **baseline** 由 build_clusters.py 一并产出。
--    「试了聚类、量出它在这份数据上不成立、换成直接优化多样性」这个过程
--    本身就是第 5 周报告的材料。
--
-- ⚠️ **必须离线预计算，不能请求时算。** MMR 要拉全部 4,439 条向量做 N 轮
--    矩阵乘 —— 正是 serverless 架构禁止的事（放弃 Render 常驻内存的同一条理由）。
--    贪心序列有**前缀性质**：取前 n 项就是 n 题的解，所以存一个位次列就够，
--    不需要为每个 n 各存一份。
ALTER TABLE anime_profile ADD COLUMN IF NOT EXISTS mmr_rank smallint;

-- 排序池 = TV/WEB · 非续作根 · **非 nsfw** · vec 非空。池外的作品此列为 NULL。
--
-- ⚠️ **池子刻意不含 nsfw**，尽管 select_items 有 include_nsfw 开关。
--    理由是按默认路径优化：把 nsfw 放进排序池的话，里番语义上极其独特、
--    会被 MMR 早早选中占掉多样性预算，而默认路径又会把它们过滤掉 ——
--    等于把预算花在永远不显示的条目上。
--    include_nsfw=True 是接口参数、前端未使用的小众路径，
--    那条路走「已排序的非 nsfw + nsfw 按热度补」即可。
--
-- ⚠️ 年份档（EXPERIENCE 的 new/mid/veteran）**不各存一份**。
--    实测全池排序后按年份过滤 vs 每档单独算，冗余差异在噪声内：
--      new  单独 0.4019 / 过滤 0.3983      mid  单独 0.3766 / 过滤 0.3853
--    不值得为此多存两列或建表。
CREATE INDEX IF NOT EXISTS idx_profile_mmr ON anime_profile (mmr_rank)
    WHERE mmr_rank IS NOT NULL;

-- ============================================================
-- 验收
-- ============================================================
--   SELECT count(*) FROM anime_profile WHERE mmr_rank IS NOT NULL;   -- ≈ 4,439
--   SELECT mmr_rank, name_cn FROM anime_profile
--    WHERE mmr_rank IS NOT NULL ORDER BY mmr_rank LIMIT 12;
--
-- ⚠️ 位次应当**无重复、从 1 连续**。有重复说明 build_clusters.py 跑了一半。
--   SELECT count(*), count(DISTINCT mmr_rank) FROM anime_profile WHERE mmr_rank IS NOT NULL;
