-- ============================================================
-- 010 —— 账号系统（第 6 周）：注册 / 登录 / 评分持久化 / 问答配额
-- ============================================================
-- schema 在设计文档 §4「用户表」里第 1 周就定好了，这里照做，
-- 只多一张 §4 没有的 ask_log —— 它是 2026-08-24 新加的需求
-- （每人 24 小时 10 条问答）的存放处，理由见该表上方注释。
--
-- ⚠️ **这是请求路径第一次写库。** 此前 src/ 下的所有请求路径模块
--    （retrieve / voice / related / router / find）都是只读的，
--    CLAUDE.md C 节那句「src/ 下的请求路径模块都不写库」是在描述现状，
--    不是铁律 —— 账号功能按定义就要写。记在这里免得以后有人当铁律用。
--
-- ⚠️ **游客路径完全不受影响。** 未登录用户的评分仍然只在 localStorage，
--    服务端零写入（设计文档「双轨会话」）。这三张表只在登录后才有行。
--
-- 幂等：可重复执行。
-- ============================================================

BEGIN;

-- ============================================================
-- app_user —— 账号
-- ============================================================
-- 🚨 **表名不能叫 user** —— 那是 Postgres 保留字，不加引号查询直接报错。
--    设计文档 §4 专门警告过这条。
--
-- ⚠️ **不存任何 PII**：没有昵称、头像、生日。账号唯一的作用是绑定评分。
--    存得越少，泄露时的损失越小，也不需要处理「删号要删哪些数据」。
CREATE TABLE IF NOT EXISTS app_user (
    user_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ⚠️ **存归一化后的邮箱**（小写 + 去首尾空白），由 src/auth.py 统一处理。
    --    不做这一步的话 Kevin@x.com 和 kevin@x.com 会是两个账号，
    --    而用户认为它们是同一个 —— 唯一约束在这种情况下形同虚设。
    -- 📌 MVP 不做邮箱验证（设计文档 §4 已定），所以 unique 只防重复注册，
    --    不代表这个邮箱真的属于注册者。已知缺口，不是遗漏。
    email         text NOT NULL UNIQUE,

    -- argon2id 的完整编码串（含算法、参数、salt），不要另存 salt 列。
    -- 换参数时旧串仍能验证，argon2 自己从串里读参数。
    password_hash text NOT NULL,

    created_at    timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz
);

-- ============================================================
-- user_rating —— 注册用户的评分（游客的等价物是 localStorage）
-- ============================================================
-- ⚠️ **主键 (user_id, subject_id)：同一部番只留最新分。**
--    一个用户可以多次作答问卷，会反复对同一部番产生行 —— 走 upsert
--    而不是 append，否则一部番会有多条互相矛盾的分数。
--
-- ⚠️ **「没看过」不写行，用缺失表示**（设计文档 §4）。不要用 score = 0 占位：
--    0 分在打分链路里是「极度难看」，与「没看过」是完全不同的信号。
CREATE TABLE IF NOT EXISTS user_rating (
    user_id    integer NOT NULL REFERENCES app_user (user_id) ON DELETE CASCADE,
    subject_id integer NOT NULL REFERENCES anime_profile (subject_id) ON DELETE CASCADE,

    -- ⚠️ 存的是**作答选项**，不是算好的分数与置信度。
    --    映射只在 questionnaire.to_rating() 一处维护 —— 把映射结果存进库
    --    等于把它固化在数据里，将来调 WISH_CONFIDENCE 就得重写全表，
    --    而且历史行会带着旧口径，静默污染推荐质量。
    --    这与「前端传 choice 不传分数」是同一条纪律的第三次应用。
    choice     text NOT NULL CHECK (choice IN ('seen', 'wish', 'pass')),
    -- 仅 choice='seen' 时有值。CHECK 把这条不变式钉在库里，
    -- 而不是只靠应用层记得 —— 应用层会忘，约束不会。
    score      real CHECK (score IS NULL OR (score >= 1 AND score <= 10)),

    -- 'questionnaire' = 问卷里被引导打的分；'manual' = 用户主动搜出来打的分。
    -- ⚠️ 两者置信度不同，设计文档 §4 为后续加权预留了这个字段。现在不用，别删。
    source     text NOT NULL DEFAULT 'manual'
               CHECK (source IN ('questionnaire', 'manual')),

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, subject_id),

    -- seen 必须有分，非 seen 必须没分。两个方向都要管：
    -- 只管前者的话，pass 带着一个 8 分躺在库里，取出来就是错的偏好信号。
    CONSTRAINT user_rating_score_matches_choice CHECK (
        (choice = 'seen' AND score IS NOT NULL) OR
        (choice <> 'seen' AND score IS NULL)
    )
);

-- 推荐/问卷都是「取这个用户的全部评分」，主键前缀已覆盖，不另建索引。

-- ============================================================
-- ask_log —— 问答用量（每人 24 小时 10 条）
-- ============================================================
-- 🚨 **为什么要建表而不是内存计数**：线上是 Vercel serverless，
--    每个函数实例各自独立、随时被回收，**进程内计数器在架构上就不成立**
--    （与 A.6「永远不能在函数里加载模型」同一个根因：没有常驻状态）。
--    ⇒ 唯一的共享状态是数据库。
--
-- ⚠️ **判据是滚动 24 小时窗口，不是自然日。** 自然日会让人在 23:59 用完 10 条、
--    00:01 再用 10 条，等于 2 分钟内 20 条；滚动窗口没有这个洞。
--    代价是 count(*) 而不是读一个计数列 —— 每人每天最多 10 行，可以忽略。
--
-- 📌 顺带得到一份问答用量记录，将来做用量分析/评测抽样时是现成的。
--    ⚠️ 但**不存回答正文**：那是几百字 × 每人每天 10 条，纯属浪费；
--    要复现某次回答该看的是检索层的 chunk_id，不是把答案抄一份。
CREATE TABLE IF NOT EXISTS ask_log (
    ask_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    integer NOT NULL REFERENCES app_user (user_id) ON DELETE CASCADE,

    -- 问句原文。留着是为了让用户看到自己问过什么（前端的历史列表），
    -- 长度与 AskRequest.question 的上限一致（200）。
    question   text NOT NULL,
    -- 实际走的分支，排查「配额被什么消耗掉了」时有用。
    route      text,

    created_at timestamptz NOT NULL DEFAULT now()
);

-- 配额查询恒为 WHERE user_id = ? AND created_at > now() - interval '24 hours'，
-- 复合索引让它走索引扫描而不是按 user_id 捞出全部历史再过滤。
CREATE INDEX IF NOT EXISTS idx_ask_log_user_time
    ON ask_log (user_id, created_at DESC);

COMMIT;
